### ISSUE TITLE
"Why choose Easybank?" grid box-model issues

### ISSUE THREAD

**Issue by veritasnz** [kebin20/easybank-landing-page#1]
<img width="1420" alt="Screen Shot 2023-01-19 at 9 33 10 AM" src="https://user-images.githubusercontent.com/7684225/213289852-2f9c1fb9-e874-4f8b-816a-70a62db277fb.png">

1. Shouldn't need to show/hide h3 tag
  - This should be done with responsive design and changing the text size with media queries
  - p-tag also shouldnt need mx-auto
2. You are setting the width of each container as 1/4, which is fine, but then creating the gaps between the content with margins. Use flex-gap for this instead.
3. Unneeded margin beneath image. Again, this is a pretty simple layout (image, title, description), and what you've got seems really complicated! All the vertical margins and text sizes could be done with media queries

**Comment by kebin20** [comment]
All fixed! Took out all the margins, added proper padding where needed and used gap to add space between each container. after doing this, everything lined up nicely! 

I saw that my hero section will also need work too, so I'll get around to fixing that when I'm free
