### ISSUE TITLE
"Latest Articles" box model issues

### ISSUE THREAD

**Issue by veritasnz** [kebin20/easybank-landing-page#2]
<img width="1145" alt="Screen Shot 2023-01-19 at 9 32 30 AM" src="https://user-images.githubusercontent.com/7684225/213291348-62b6ac55-80eb-4de1-ad0c-55cf5b513002.png">

1. You're giving padding to each sub-child inside of the Article card. You should instead wrap the entire content part of the card in a div and set the padding _once_ there.
  - Also, use **_semantic HTML_** (ul, li, article tags and so on)
```
<ul>
  <li>
    <a href="...">
      <article>
        <img src="...">
        <div class="px-8 py-10"> <!-- Set the padding once here -->
          <p>Author name</p>
          <h4>Title</h4>
          <p>Description</p>
        </div>
      </article>
    </a>
  </li>
  ...
</ul>
```

2. You are creating problems for yourself by not wrapping parent containers with padding. If you wrapped the container with some horizontal padding, you wouldn't need to give padding to the title of the block here either. This is a similar issue to the other one, where I stated you should use flex-gap.

3. In general, you are using `space` (never seen this before btw) where I would just use `gap`

**Comment by kebin20** [comment]
Thanks for the tips! I've now significantly reduced the use of margins and set padding on the parent containers, plus used the gap property. It made the job a whole lot easier too!
